---
#
# Usage:
#   $ sudo ceedling [clean|clobber] options:project-sm test:Sm
#   $ sudo ceedling [clean|clobber] options:project-action test:SmAct
#

:project:
  :use_exceptions: FALSE
  :use_test_preprocessor: TRUE
  :use_auxiliary_dependencies: TRUE
  :build_root: build
  :which_ceedling: ../../third-party/ceedling
  :test_file_prefix: test_
  :options_paths: 
  - .

:environment: []

:extension:
  :executable: .out

:paths:
  :test:
    - +:test
    - -:test/support
  :source:
  :include:
    - inc
    - ../../third-party/rkh/source/fwk/inc
    - ../../third-party/rkh/source/mempool/inc
    - ../../third-party/rkh/source/queue/inc
    - ../../third-party/rkh/source/sm/inc
    - ../../third-party/rkh/source/sma/inc
    - ../../third-party/rkh/source/tmr/inc
    - ../../third-party/rkh/source/trc/inc
    - ../../third-party/rkh/source/portable/test
  :support:
    - test/support
    - ../../third-party/rkh/third-party/unitrazer
    - ../../third-party/rkh/source/fwk/src
:defines:
  :common: &common_defines [__TEST__]
  :test:
    - *common_defines
    - TEST
  :test_preprocess:
    - *common_defines
    - TEST

:cmock:
  :when_no_prototypes: :warn
  :plugins: [ignore_arg, ignore, callback]
  :mock_prefix: Mock_
  :callback_after_arg_check: TRUE
  :when_ptr: :compare_ptr
  :enforce_strict_ordering: TRUE
  :treat_as:
    uint8:    HEX8
    uint16:   HEX16
    uint32:   UINT32
    int8:     INT8
    bool:     UINT8

#:tools:
# Ceedling defaults to using gcc for compiling, linking, etc.
# As [:tools] is blank, gcc will be used (so long as it's in your system path)
# See documentation to configure a given toolchain for use

:tools_test_linker:
  :arguments:
    - -lm

:tools_test_compiler:
  :arguments:
    - -D__UNITRAZER_LIB__
    - -Wall
    - -Wno-pointer-sign
    - -Wno-missing-braces

:tools_gcov_linker:
  :arguments:
    - -lm

:gcov:
  :html_report_type: detailed

# LIBRARIES
# These libraries are automatically injected into the build process. Those specified as
# common will be used in all types of builds. Otherwise, libraries can be injected in just
# tests or releases. These options are MERGED with the options in supplemental yaml files.
:libraries:
  :placement: :end
  :flag: "${1}"
  :common: &common_libraries []
  :system:
    - ../../third-party/rkh/third-party/unitrazer/unitrzlib.a
    - -lstdc++

:module_generator:
  :inc_root: inc/

:plugins:
  :enabled:
    - stdout_pretty_tests_report
    - module_generator
    - gcov

